### ISSUE TITLE
cứu với bác ơi

### ISSUE THREAD

**Issue by Luongzz** [nullmastermind/py-chatgpt-discord-bot#1]
Traceback (most recent call last):
  File "C:\Users\Yoshino\Desktop\Bot\bot gpt\py-chatgpt-discord-bot-master\main.py", line 5, in <module>
    from discord import SlashCommand, Option
ImportError: cannot import name 'SlashCommand' from 'discord' (C:\Users\Yoshino\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\__init__.py)

**Comment by nullmastermind** [comment]
có vẻ b cài nhầm thư viện
bạn xoá discord đi r cài lại py-cord

**Comment by nullmastermind** [comment]
bạn nên tạo riêng 1 env mới r chạy `pip install --no-cache-dir -r requirements.txt` hoặc dùng docker
